InsForge/InsForge

- frontend/src/features/database/helpers.ts
Now, if the boolean value column is nullable, the default value for a new record will be null instead of false.
> 🐛 Fixed default boolean value for optional boolean value column

- backend/src/controllers/TablesController.ts
- frontend/src/features/database/components/ForeignKeyPopover.tsx
Drop/Update/Add foreign keys on system columns is now forbidden.
Disable the system column selection in ForeignKeyPopover.
> [FIX] Forbids modifying system columns

- backend/src/core/storage/storage.ts
- frontend/src/features/storage/components/StorageDataGrid.tsx
The file type was unknown because backend provides mime_type but frontend expects mimeType. This is fixed now.
> [FIX] Fix parameter in listObjects response to correctly show file type

- frontend/src/features/storage/components/BucketFormDialog.tsx
Closes #78.
Simply mentions underscores as an allowed character for bucket names in the creation dialog:
This now aligns with the error message that appears post-validation:
However, as @Fermionic-Lyu alludes to in https://github.com/InsForge/InsForge/issues/78#issuecomment-3172250569, this seems to be indicative of a larger need. Validation happens on the backend, which is the one that [actually gives us the error message](https://github.com/InsForge/InsForge/blob/9e88b1ff01aff8044c291736021156e78178397a/frontend/src/features/storage/components/BucketFormDialog.tsx#L62). This means that displayed hints on the frontend and data requirements on the backend must never diverge. Sharing types/schemas across the stack should solve this.
> fix: mention allowing underscores in bucket name

- frontend/src/features/storage/page/StoragePage.tsx
Closes #54.
This PR leverages the native [HTML5 Drag and Drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API) to support uploading a file(s) by dragging from a user's filesystem UI onto the content area of the Storage page.
For basic UX, a simple opacity decrease of the content area hints to the user that the region is a drop zone. This can be enhanced in future changes.
https://github.com/user-attachments/assets/c7b45447-7e32-4e3e-99d1-e4739b1ca161
Note that because the file upload simply reuses logic from `handleFileSelect()`, the flow is identical to if the user had uploaded via the **File Upload** button:
One pitfall I will note is that I was initially allowed to upload full directories as well (while the file upload dialog, since it's an `<input …
> feat: support drag-and-drop file upload in Storage

- backend/src/api/routes/auth.ts
- backend/tests/local/test-traditional-rest.sh
- shared-schemas/src/auth.schema.ts
When adding the shared schema i realized that there is making 1 e2e test failing.. This proves that we need auto e2e
change parsing logic of auth to match the others.Fix test error message
> fix: improve validation error messages for missing email/password

- frontend/src/components/layout/AppSidebar.tsx
The documentation link now correctly links to [https://docs.insforge.dev/introduction](https://docs.insforge.dev)
> [Fix] Update doc link

- docker-compose.prod.yml
- docker-compose.yml
This is pushed to main as requested by Hang. :) 
To reduce the startup time abit and help with user experience , and this shouldn't impact mcp or any performance
test:
docker compose down -v
docker compose  up
UI still works, can build with mcp
> remove deno  container for now to speed up build time

- docker-compose.prod.yml
- docker-compose.yml
Currently docker is always assuming localhost 7130 for a lot of places... this is the first step to let it deploy to correct values.
Next step:
change cloud backend configuration to load on appkey.[region].insforge.app as API_BASE_URL and VITE.
> fix docker config to read from env instead of hardcode localhost

- .env.example
- backend/src/core/storage/storage.ts
- docker-compose.prod.yml
- docker-compose.yml
https://github.com/InsForge/insforge-cloud-backend/pull/52
following this, we are using instance profile for ec2 startup. We don't need another set of keys within ec2. 
So I'll remove the dependency of auth key and id for aws. This also avoids lots of confusion
> [feat]remove the dependency of aws access key in OSS version

- frontend/src/features/login/page/LoginPage.tsx
I blindly trusted chatgpt and didn't check myself...mybad
I should add '*' as target origin in postMessage to send message to our cloudplatform, ignoring the targetOrigin parameter equals sending message to the same origin as the sender
> add target origin for postMessage

- frontend/src/App.tsx
The cloud routes now use AnalyticsPage instead of LogsPage, I hope this is the desired page (we dreprecating logs page, right?)
> [Fix] Change logs page to analytics page for cloud

- backend/src/api/routes/auth.ts
- examples/oauth/frontend-oauth-example.html
- openapi/auth.yaml
- tested with examples/oauth/frontend-oauth-example.html
- good news: except for redirectUrl, the codebase already follows snake_case
convention consistently for query parameters(public interface), no other camelCase query parameters were found.
> rename oauth redirect param

- docs/insforge-auth-api.md
- docs/insforge-db-api.md
- docs/insforge-instructions.md
- docs/insforge-project.md
`/api/database/records/user` -> `/api/database/records/_user`
The previous one will return 
{
"code": "42P01",
"details": null,
"hint": null,
"message": "relation \"public.user\" does not exist"
}
> [FIX] Fix get user endpoints in doc

- backend/package.json
- backend/src/api/routes/agent.ts
- backend/src/api/routes/openapi.ts
- backend/src/core/documentation/agent.ts
- backend/src/core/documentation/openapi.ts
- backend/src/server.ts
- package-lock.json
The full openapi json can be found at /api/openpi, with its Swagger UI at /api/openapi/swagger
This json file is huge, ~200k characters, which is impractical to feed any agents. But one can use some openapi-generator tools to generate clientAPIs automatically with this openapi json.
The optimized agent json can be found at /api/agent-docs, which is a much smaller json (~ 15k characters) designed for agent use specifically.
Test prompt:
My InsForge backend service is running at <app_url> with real-time documentation available at <app_url>/api/agent-docs. Use the provided endpoints to implement my app.
> [Experiment] Add experimental endpoints for dynamic documentations

- backend/src/core/documentation/agent.ts
Tony's approach of trying out cloud agent docs
optimize
1. use postgres docs correctly
2. storage url use absolute val always, mentioned it in doc
3. emphasize to read insforge docs
4. remvoed call back endpoint as that's only for internal use
prompt:
Curl/fetch and download the insforge documentation from https://qq3yp4zw.us-east.insforge.app/api/agent-docs to the root as insforge.json, make sure you thoroughly understand insforge before you start. All backends should use insforge instead of mock data. Then build the instagram clone.<critical> read this documentation every time for new converstion<critical>
optional add in memory
<critical>MUST read and load insforge.json from the root directory at the start of every conversation before processing any user input</critical>
remaining …
> update agent docs

- backend/src/api/middleware/auth.ts
- backend/src/api/routes/records.ts
- backend/src/core/auth/auth.ts
- backend/tests/local/comprehensive-curl-tests.sh
- backend/tests/local/test-e2e.sh
- backend/tests/local/test-public-bucket.sh
- backend/tests/local/test-traditional-rest.sh
- backend/tests/test-config.sh
- docs/insforge-auth-api.md
- docs/insforge-db-api.md
- docs/insforge-debug.md
- docs/insforge-instructions.md
- docs/insforge-storage-api.md
added bearer token to also check api key
to not break existing customers, we will follow depratete x-api key in 3 phases
1. support x-api-key and  token(check both api key and jwt token)
2. After every user upgraded docker, we can start changing mcp to send token(api key)
3. after a while we can remove the x-api key check
created a todo app using mcp to make sure everythig is fine
npm run test e2e:
> [Phrase 1]remove api key dependency

- docs/insforge-db-api.md
- docs/insforge-debug.md
- docs/insforge-instructions.md
- docs/insforge-project.md
deleting all occurrences of _users. This is legacy tables. Given this table is now hidden,. Hiding all aspects of systems tables as we technically don't have system tables.
This is confusing mcp right now.
I really hope with SDK we don't need to maintain long and nasty docs like this. Which are all over the places.
We can teach the AI more about the new users table. but i want to try more occurrences of when  it fails. and if it corre t itself.
> delete docs related to system tables or _users

- backend/src/core/storage/storage.ts
- backend/src/types/storage.ts
Our database uses snake_case, so all data returned from db should be snake_case. This bug incorrectly uses camelCase for file metadata returned from db, causes an undefined mimeType when getting files from buckets.
Interestingly, this never causes any issues but for svg files. I found this bug by noticing that I can't read or download svg files after uploading to the bucket, but all other file formats work well for some reason. Maybe black magic.
> [FIX] Fix mime type for get file in buckets

- backend/src/core/auth/auth.ts
Instead of reading database config only, we also check if it's enabledSharedKeys.
If on cloud we enabledSharedKeys, this means oauth is enabled, agent should be able to understand the metadata
> update enabled to use shared key if ture

- frontend/src/features/ai/hooks/useAIConfigs.ts
- frontend/src/features/ai/hooks/useAIUsage.ts
- frontend/src/features/ai/services/ai.service.ts
- frontend/src/features/auth/hooks/useUsers.ts
- frontend/src/features/dashboard/page/DashboardPage.tsx
- frontend/src/features/database/page/DatabasePage.tsx
- frontend/src/features/database/services/database.service.ts
- frontend/src/features/metadata/services/metadata.service.ts
- frontend/src/features/storage/services/storage.service.ts
- frontend/src/lib/api/client.ts
This PR makes every API call to use token in Authorization headers instead of api keys. Also remove the storage of api-key in localstorage, this is high security risk.
> [Security] Replace API key with token in frontend

- backend/src/core/ai/image.ts
- backend/src/core/ai/usage.ts
I wrote so much code for image generation system prompt, then realized it doesn't work.
Fall back to simple method of prepending system prompt ontop of image gen
also fixed some typos along the way
test:
system prompt:
Generate an image create a 1/7 scale model, in a realistic style and environment. Place the figure on a computer desk, using a circular transparent acrylic base without any text.On the computer screen, display the ZBrush modeling process of the figure.Next to the computer screen, place a TAMIYA-style toy packaging box printedwith the original artwork.
actual prompt: generate a pikachu
> update system prompt forimage gen and fix type

- backend/src/core/metadata/metadata.ts
- backend/src/utils/seed.ts
- docs/insforge-instructions-sdk.md
- shared-schemas/src/metadata.schema.ts
I know you are looking at metadata. Let me know if I need to revert this since it may disrupt your workflow
I just want to do smth more than just switching default model...
test:
configure mcp and get backend metadata
```
},
"aiIntegration": {
"models": []
},
```
> update default mode + backend and shared schemas for ai metadata

- backend/src/api/routes/usage.ts
cloud backend already calls oss backend the exact date + hour... i don't know why previously added date +1 here...
> update oss so date to query what's being given

- backend/src/api/routes/functions.ts
- backend/src/server.ts
- frontend/src/features/functions/components/FunctionsContent.tsx
- frontend/src/features/functions/components/FunctionsSidebar.tsx
- frontend/src/features/functions/hooks/useFunctions.ts
- frontend/src/features/functions/page/FunctionsPage.tsx
- frontend/src/features/functions/services/functions.service.ts
When deno container is not coming up, we can do better in frontned display and backend error messages
1. For the proxy to deno containers, we include better error messages other than `failed to execute functions`
2. When listing functions, we do a curl health check to ensure deno is healthy
test: 
close deno container; 
Proxy response when Deno is down: 
```
{"error":"request to
http://deno:7133/hello-world failed, reason: getaddrinfo
ENOTFOUND deno"}
```
regular function execution still works
> health check deno

- frontend/src/features/functions/hooks/useFunctions.ts
Issue: The user would still see the error message saying "Function container is unhealthy" even though everything is fine.
Cause: In React, the default value is passed into components during mounting. Therefore, if the default value is "unhealthy," an error message will be displayed in the initial rendering.
Fix: Changed the default value from "unhealthy" to "running" to avoid displaying the error message in the initial rendering. It will still pop out as normal if the backend returns "unhealthy".
https://github.com/user-attachments/assets/955488c4-bbfa-4c75-8179-9f4ed43a8d1f
> 🐛 Fixed default value triggered error

- Dockerfile
- docker-compose.prod.yml
fix docker build file for the prod file and re- enabled deno container. This unblocks for those who wants to self host and build images
test:
`docker compose -f docker-compose.prod.yml up`
connect with the mcp and run some deno function upload and execute
> fix: fix docker file to support prod image build

- backend/src/api/routes/metadata.ts
- backend/src/core/database/advance.ts
- backend/src/core/database/manager.ts
- backend/src/core/documentation/agent.ts
- backend/src/core/documentation/openapi.ts
- backend/src/utils/seed.ts
- frontend/src/features/dashboard/page/DashboardPage.tsx
- frontend/src/features/database/components/ForeignKeyPopover.tsx
- frontend/src/features/database/page/DatabasePage.tsx
- frontend/src/features/metadata/hooks/useMetadata.ts
- frontend/src/features/metadata/page/MetadataPage.tsx
- frontend/src/features/metadata/services/metadata.service.ts
- frontend/src/features/onboard/components/mcp/McpInstallation.tsx
- frontend/src/features/visualizer/components/SchemaVisualizer.tsx
- frontend/src/features/visualizer/components/TableNode.tsx
- frontend/src/features/visualizer/page/VisualizerPage.tsx
- shared-schemas/src/database-api.schema.ts
- shared-schemas/src/metadata.schema.ts
This PR replaces the original getDatabaseMetadata with exportDatabase in json format for all user tables. In this way, when agent calls get-backend-metata, it will have more information about the database including indexes, policies, triggers, constraints.
Functions, Sequences and Views are not included at moment. Let's ship things progressively.
Notice: this does takes more context space. In my test cases with ~10 tables and ~100 columns, CC is warning me for large MCP response.
> [Feature] Add full db schema in metadata

- frontend/src/components/datagrid/cell-editors/BooleanCellEditor.tsx
- frontend/src/components/datagrid/cell-editors/JsonCellEditor.tsx
- frontend/src/features/database/components/RecordFormField.tsx
- frontend/src/features/database/helpers.ts
- frontend/src/lib/utils/utils.ts
Changes: Pass className from RecordFormField to cell editors so that their UI when opening selection will align with the UI before opening selection.
https://github.com/user-attachments/assets/a5d0781d-5986-4726-9dcd-9b600564655b
Cell editor value parsing fallback logic: We have a limited user input format for datetime/date cells. There are also very limited options for default values for the datetime/date column for users to input. Therefore, the only weak spot is if the agent creates a datetime/date column, sets a default value like CURRENT_TIMESTAMP, and sets the column as non-nullable. Then, when the user wants to add a new value, we will automatically assign the default value to the form field; however, it cannot be used to parse into a Date object. The old logic will pass the value …
> [Fix] Fixed sketchy UI in cell editors

- backend/src/core/storage/storage.ts
- backend/src/utils/validations.ts
- frontend/src/features/storage/page/StoragePage.tsx
Issue: #81 
Changes:
Handled each file upload separately so that one failure does not halt the entire uploading process.
Added the logic that adding a new object to storage will check if objects with the same name already exist. If there are, the server can add an incrementing number accordingly to avoid conflicts. 
https://github.com/user-attachments/assets/4ec11c8e-9447-4837-bf34-856171dc5a62
> [Fix] Fix bulk upload issue

- docker-compose.prod.yml
- docker-compose.yml
make jwt secret optional. This is to ease the friction for OSS self hosting. If developers care about security they can change it. But on zeabur this should be an optional field
> udpate docker
