InsForge/InsForge

- frontend/src/components/radix/Select.tsx
- frontend/src/features/auth/components/OAuthConfiguration.tsx
- frontend/src/features/auth/components/UserFormDialog.tsx
- frontend/src/features/auth/page/AuthenticationPage.tsx
- frontend/src/features/database/components/FieldRow.tsx
- frontend/src/features/database/components/TableForm.tsx
- frontend/src/lib/hooks/useToast.tsx
1. Placeholder text in Select components are now correctly set to text-muted-foreground
2. Align the 'Delete' row button with nullable/unique checkboxes in Table Form
3. Change text in OAuth from 'Configured/Not Configured' to 'Enabled/Disabled'
4. If failed to add a user through user form, the dialog won't be closed and show the toast directly
https://github.com/user-attachments/assets/764be5bd-39ae-4857-a97e-8a7198d582de
> [UIUX] Improve several visuals and user interactions

- frontend/src/components/DataGrid.tsx
- frontend/src/features/database/page/DatabasePage.tsx
- frontend/src/features/storage/components/StorageManager.tsx
- frontend/src/features/storage/page/StoragePage.tsx
- frontend/src/rdg.css
https://github.com/user-attachments/assets/ecd3c536-b835-4835-9326-a791f14b21e4
> 💄 Added refresh state indicator & removed outline in table

- frontend/src/components/SelectionClearButton.tsx
- frontend/src/components/index.ts
- frontend/src/features/auth/page/AuthenticationPage.tsx
- frontend/src/features/database/page/DatabasePage.tsx
- frontend/src/features/storage/page/StoragePage.tsx
https://github.com/user-attachments/assets/5918ad57-519b-49ec-8d56-a2f32e208151
> 🐛 [UIUX] Fixed unselect button interaction logic

- .gitignore
- src/api/routes/functions.ts
- src/core/database/database.ts
Serverless function should not have fk on user id, MCP needs to update functions as well. Also changed timestamp to timestamp Z
added gitignore to deno lock as it auto creates if i delete that file
docker compose down -v
npm run test e2e
> Fix Serverlessfunction bug

- .github/copilot-instructions.md
I used to Claude Code to generate this and modified a little bit. Let's use AI to teach AI how to do things properly
> Create copilot-instructions.md for Github Copilot code reviews

- backend/src/api/routes/docs.ts
- docker-compose.prod.yml
- docker-compose.yml
MCP starts to fail due to path directory change
test: started a mcp server and now it can load instructions!
> [Bug Fix]update backend doc path

- backend/src/api/routes/logs.ts
- backend/src/core/analytics/analytics.ts
- backend/src/server.ts
- backend/src/types/logs.ts
- frontend/src/App.tsx
- frontend/src/components/layout/AppSidebar.tsx
- frontend/src/features/logs/components/AnalyticsLogsTable.tsx
- frontend/src/features/logs/page/AnalyticsLogsPage.tsx
- frontend/src/features/logs/page/LogsPage.tsx
- frontend/src/features/logs/services/logs.service.ts
- frontend/src/lib/utils/utils.ts
MVP version for project logging.
> Feat: add logging page in frontend.

- frontend/src/components/layout/AppSidebar.tsx
- frontend/src/components/layout/Layout.tsx
- frontend/src/components/radix/Button.tsx
- frontend/src/components/radix/Switch.tsx
- frontend/src/components/radix/Tabs.tsx
- frontend/src/lib/hooks/useMediaQuery.ts
- frontend/src/rdg.css
https://github.com/user-attachments/assets/ffca665d-e3fd-4c3e-99ae-9f25eb4f5a1a
1. For screen width < 1536px, AppSidebar now respond to Hover instead of Collapse button. The collapse button is hidden for screen width < 1536px.
2. Also makes the AppSidebar expanding/collapsing animation a little smoother.
3. Removed focus-visble outlines.
> [UI] Sidebar UI fix & remove ugly focus outlines

- frontend/src/features/database/components/DatabaseDataGrid.tsx
- frontend/src/features/database/components/DateCellEditor.tsx
- frontend/src/features/database/components/TableForm.tsx
- frontend/src/features/database/page/DatabasePage.tsx
- frontend/src/lib/utils/database-utils.ts
https://github.com/user-attachments/assets/6cb9c04b-501a-4482-9f4a-a1dd55febacf
1. Update record request won't be sent now if oldValue === newValue.
2. Added a Confirm Discard dialog for TableForm if the form is dirty. 
3. Fixed miscellaneous bugs in UIUX
This PR resolves #9, resolves #49 and resolves #50
> [UIUX] Fix record update & Add discard dialog for table form

- docs/insforge-auth-api.md
- docs/insforge-db-api.md
- docs/insforge-debug.md
- docs/insforge-instructions.md
- docs/insforge-project.md
- docs/insforge-storage-api.md
emphasize that we need to use curl.exe for windows.
also curl request all the examples given are cross platform compatible
emphasized some poitns on mandatory curl
> [Docs]Windows compatible documentation

- backend/src/core/database/database.ts
- backend/src/lib/better-auth.ts
disable generate uuid.  and change all sytem tables to uuid
docekr compose down -v
docker compos up
npm run test:e2e
> use uuid for database

- .github/workflows/docker-build.yml
We need to merge this to main to test the
> update workflow push branch for image release

- frontend/src/components/mcp/mcp-helper.ts
> 🐛 Fixed mcp install command

- backend/src/api/routes/auth.ts
- backend/src/core/auth/auth.ts
- frontend/src/features/auth/services/auth.service.ts
- frontend/src/features/login/page/LoginPage.tsx
- frontend/src/lib/contexts/AuthContext.tsx
1. Rename login -> loginWithPassword
2. Add loginWithAuthorizationCode
The LoginPage now check if there is an authorizationToken in the search parameter. If there is, then call /admin/session/exchange from backend and try to get an admin token with the authorizationToken. If there isn't, then use the original email/password login.
Also suggesting change authorizationToken -> authorizationCode to for better distinguishment with access token.
Also suggesting we remove the hard coded password in LoginPage...
docker-compose up passed
npm run build passed
> [Feature] Add login with authorization code

- backend/src/api/routes/auth.ts
- backend/src/core/auth/auth.ts
- frontend/src/features/auth/services/auth.service.ts
- frontend/src/features/login/page/LoginPage.tsx
- shared-schemas/src/auth-api.schema.ts
- shared-schemas/src/auth.schema.ts
> [Fix] Change naming from authorizationToken to authorizationCode

- mcp/package.json
Update mcp version as we upgraded mcp code
https://github.com/InsForge/InsForge/pull/106
confirmed it works by manual publihs
and creating an app off from cloud
> update mcp package version

- backend/src/api/routes/config.ts
- backend/src/api/routes/metadata.ts
- backend/src/core/metadata/metadata.ts
- backend/src/types/storage.ts
- backend/src/utils/environment.ts
- frontend/src/components/FeatureSidebar.tsx
- frontend/src/features/auth/components/OAuthDialog.tsx
- frontend/src/features/dashboard/page/DashboardPage.tsx
- frontend/src/features/database/components/TableSidebar.tsx
- frontend/src/features/database/page/DatabasePage.tsx
- frontend/src/features/metadata/services/metadata.service.ts
- frontend/src/features/storage/components/StorageSidebar.tsx
- frontend/src/features/storage/page/StoragePage.tsx
- frontend/src/features/visualizer/components/AuthNode.tsx
- frontend/src/features/visualizer/components/BucketNode.tsx
- frontend/src/features/visualizer/components/SchemaVisualizer.tsx
- frontend/src/features/visualizer/components/TableNode.tsx
- frontend/src/features/visualizer/page/VisualizerPage.tsx
- shared-schemas/src/auth.schema.ts
- shared-schemas/src/database.schema.ts
- shared-schemas/src/metadata.schema.ts
1. Refined metadata schema, namings, endpoints
2. Visualizer can now get object count in each bucket
3. Visualizer now have the correct Oauth config
> [CHORE] Refine metadata & get bucket object count in metadata

- backend/package.json
- backend/src/core/analytics/analytics.ts
- package-lock.json
We cannot display the logs in EC2 prod. 
We enabled the Cloudwatch logs and update the AnalyticsManager to display logs in EC2 prod
And make sure the local env works:
> Cloudwatch logs frontend

- backend/src/api/routes/config.ts
- frontend/src/features/auth/components/OAuthDialog.tsx
- frontend/src/features/dashboard/page/DashboardPage.tsx
- frontend/src/features/login/page/CloudLoginPage.tsx
- frontend/src/features/storage/components/BucketFormDialog.tsx
- frontend/src/features/visualizer/components/BucketNode.tsx
- frontend/src/features/visualizer/components/SchemaVisualizer.tsx
1. Fix shared keys display bug in OAuth config
2. Adjust visualizer visuals
3. Fix brief auth error info when login with authorizationCode from cloud
> [Fix] Fix miscellaneous issues

- openapi/records.yaml
- openapi/tables.yaml
https://github.com/InsForge/insforge-docs/pull/6
when testing out mintlify pr. I realized that there are minor bugs in open api yaml
1. if we include colon, we need to wrap it around quotes else it can't parse
2. delete table api endopintn already defined above, it's declaring it again
> update open api yaml

- frontend/src/features/database/page/DatabasePage.tsx
- frontend/src/features/database/services/database.service.ts
Our database page searching & pagination (only shows the first 50 records) are not working. This PR fixes it
https://github.com/user-attachments/assets/200327da-6cad-4f03-9669-cf4fc62d28c2
> [FIX] Fix database pagination

- frontend/src/App.tsx
- frontend/src/components/layout/CloudLayout.tsx
- frontend/src/features/dashboard/page/DashboardPage.tsx
- frontend/src/features/login/components/PrivateRoute.tsx
- frontend/src/features/login/page/LoginPage.tsx
- frontend/src/features/visualizer/components/TableNode.tsx
1. Fixed loading white blink when hard refreshing the iframe in cloud
2. Fixed foreign key edges now showing in visualizer if the foreign key is not a primary key
> [FIX] Fix loading visual/visualizer fk bug

- frontend/src/rdg.css
This 1 line fix is actually very hard to find and stumbling CC for 1 hour.
> [FIX] Fix frozen header row when sorting column

- backend/src/core/storage/storage.ts
- docs/insforge-auth-api.md
- docs/insforge-db-api.md
- docs/insforge-instructions.md
- docs/insforge-project.md
- docs/insforge-storage-api.md
1. mention examples don't include special characters, this result in curl always failing sometimes
2. storage always use absolute value for file path. We previosly tried using relative path but AI always makes mistakes. lets try absolute paths now
3. Mention about user table(hvaen't mentioned about rls and the ability to curl, but so far it follwos the user workflow of loging in and processing)
npm run test:e2e
build an instagram clone(AGAIN)
> Fix MCP docs 

- backend/src/api/routes/records.ts
- backend/src/controllers/TablesController.ts
- frontend/src/components/ConfirmDialog.tsx
- frontend/src/components/DataGrid.tsx
- frontend/src/components/FeatureSidebar.tsx
- frontend/src/components/SearchInput.tsx
- frontend/src/components/radix/Select.tsx
- frontend/src/features/auth/components/UsersManagement.tsx
- frontend/src/features/auth/page/AuthenticationPage.tsx
- frontend/src/features/database/components/ColumnTypeSelect.tsx
- frontend/src/features/database/components/ForeignKeyPopover.tsx
- frontend/src/features/database/components/TableForm.tsx
- frontend/src/features/database/components/TableFormColumn.tsx
- frontend/src/features/database/page/DatabasePage.tsx
- frontend/src/features/storage/page/StoragePage.tsx
https://github.com/user-attachments/assets/ec6d0ab8-b964-411d-8221-a1d86e91f456
> 💄 Updated dark theme UI & foreign key popover ui

- backend/src/api/routes/database.ts
- backend/src/api/routes/records.ts
- backend/src/api/routes/tables.ts
- backend/src/controllers/database.ts
- backend/src/core/database/database.ts
- backend/src/server.ts
- backend/tests/manual/test-database-advance.sh
- backend/tests/manual/test-postgrest-stability.sh
- backend/tests/manual/test-users.sql
- shared-schemas/src/database-api.schema.ts
add new test script: /test-database-advance.sh, the result is as below:
```
=========================================
Database Advance Tests Complete
=========================================
All tests have been executed.
Check the responses above to verify all functionality.
Key things to verify:
Raw SQL Tests:
- Posts table existence check
- Index creation and verification
- SQL execution with proper responses
Export Tests:
- SQL exports should contain CREATE TABLE statements
- When includeData=true, INSERT statements should be present
- When includeData=false, only schema should be exported
- JSON exports should have 'schema' and 'rows' properties
- Invalid requests should return appropriate error messages
Import Tests:
- File uploads should be processed correctly
- SQL files should be …
```
> Feat: add three endpoints: /rawsql /export /import

- backend/src/api/routes/metadata.ts
add the query endpoint for review.
```
$ curl -X GET "http://localhost:7130/api/metadata/users" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer {token}"
{"users":
{"schema":
[{"columnName":"id","dataType":"uuid","characterMaximumLength":null,"isNullable":"NO","columnDefault":null},
{"columnName":"nickname","dataType":"text","characterMaximumLength":null,"isNullable":"YES","columnDefault":null},
{"columnName":"avatar_url","dataType":"text","characterMaximumLength":null,"isNullable":"YES","columnDefault":null},
{"columnName":"birthday","dataType":"date","characterMaximumLength":null,"isNullable":"YES","columnDefault":null},
{"columnName":"extra","dataType":"jsonb","characterMaximumLength":null,"isNullable":"YES","columnDefault":null}, …
```
> feat: enable query the schema of a single table

- backend/src/api/routes/auth.ts
- docs/insforge-auth-api.md
- shared-schemas/src/auth.schema.ts
Cherry picked the commit to main to fix the redirect url doc bug
> change mcp auth doc, and add check for redirect_uri for oauth request.

- docs/insforge-instructions-sdk.md
- docs/insforge-project-sdk.md
Added how to use AI  in insforge instructions. Also investigating can we put everything into instructions sdk docs, so we don't need other sdk docs.
currently the sdk follows the openai input structure
but slighly differ than the openai output structure. i'm still testing locally to see if it works
> udpate ai docs

- frontend/src/components/PromptDialog.tsx
This PR fixs the theme issue in PromptDialog.
> [FIX] Fix prompt dialog light theme

- backend/migrations/006_modify-ai-usage-table.sql
- backend/src/api/routes/ai.ts
- backend/src/core/ai/chat.ts
- backend/src/core/ai/image.ts
- backend/src/core/ai/usage.ts
- frontend/src/features/ai/helpers.ts
- frontend/src/features/ai/page/AIPage.tsx
1. Added migration 006 to fix the following issues:
- AI configs are now deletable even if it has AI usage records. The config_id will be set to null
- Added user_id, user_email to _ai_usage table to audit usage from users
2. Fix AI Config UI on dashboard to hide openrouter
> [FIX] Fix AI usage table

- frontend/src/features/login/page/CloudLoginPage.tsx
This resolves [https://github.com/InsForge/insforge-cloud/issues/61](https://github.com/InsForge/insforge-cloud/issues/61)
There is room for further optmization but I'll use the simple solution for now
> [FIX] Fix visualizer blink in cloud hosting

- frontend/src/features/database/page/DatabasePage.tsx
This resolves [https://github.com/InsForge/insforge-cloud/issues/66](https://github.com/InsForge/insforge-cloud/issues/66)
> [FIX] Hide add records button for users table

- frontend/src/components/DataGrid.tsx
Adjusted the top margin to match the new row height. 
Resolves: https://github.com/InsForge/insforge-cloud/issues/68
> [UI/Fix] Updated loading state top margin to align

- mcp/package.json
- mcp/src/index.ts
- package-lock.json
Sorry my bad, that PR get merged into devAug31...
💩
> [Feature] Add run-raw-sql for mcp

- backend/src/core/ai/image.ts
- backend/src/core/analytics/analytics.ts
- backend/src/core/analytics/providers/analytics.provider.interface.ts
- backend/src/core/analytics/providers/cloudwatch.provider.ts
- backend/src/core/analytics/providers/localdb.provider.ts
- backend/src/core/metadata/metadata.ts
- frontend/src/features/logs/components/LogsTable.tsx
- frontend/src/features/logs/page/AnalyticsLogsPage.tsx
- frontend/src/features/logs/services/logs.service.ts
> fixed: cloudwatch log query

- docs/insforge-instructions-sdk.md
- frontend/vite.config.ts
- functions/worker-template.js
1. docs changed to create client to uniform docs
2. Add a proxy from 7131 functions to 7130, this is to help localhost only since our base url displayed on mcp and docs will be 7131
3. don't set a version for deno sdk
> update prompt and proxy

- openapi/functions.yaml
> update opanapi yaml

- frontend/src/features/onboard/components/mcp/mcp-helper.tsx
Phase 2: 
Cursor installation string
confirm installed mcp stil works by getting metadat
> update mcp installation string

- backend/src/server.ts
- package-lock.json
- package.json
After merged, we can run command on main branch to release a new version:
```
npm run release:major/minor/patch
```
Or perform a dry run to see what actions release-it would take without actually performing them:
```
npm run release:dry
```
I also change the health endpoint to return current version as below:
```
$ curl http://localhost:7130/api/health                           
{"status":"ok","version":"0.2.9","service":"Insforge OSS Backend","timestamp":"2025-09-25T23:51:26.667Z"}
```
> Feat: add release plugin

- backend/src/api/routes/functions.ts
- backend/src/core/functions/functions.ts
- shared-schemas/package.json
- shared-schemas/src/functions-api.schema.ts
- shared-schemas/src/functions.schema.ts
- shared-schemas/src/index.ts
npm run test:e2e passes
uses the route , service model correctly.  hopefully. Please help me double check
use shared schemas for functions
> refractor functions to use shared schemas and proper model

- frontend/src/features/database/components/ForeignKeyPopover.tsx
Fixed the issue where the select value was not displaying. 
https://github.com/user-attachments/assets/fb836864-98ea-49a8-88c5-dc7e10336162
> [Fix] Fixed foreign key popover display issue

- .env.example
- backend/src/api/routes/auth.oauth.ts
- backend/src/core/auth/auth.ts
- backend/src/core/auth/oauth.ts
- backend/src/utils/seed.ts
- docker-compose.prod.yml
- docker-compose.yml
- frontend/src/features/auth/components/OAuthConfigDialog.tsx
- frontend/src/features/functions/components/FunctionRow.tsx
- frontend/src/features/onboard/components/mcp/CursorDeeplinkGenerator.tsx
- frontend/src/features/onboard/components/mcp/McpInstallation.tsx
- frontend/src/features/onboard/components/mcp/mcp-helper.tsx
- frontend/src/lib/utils/utils.ts
This PR supports developer to put OAuth configs in .env and load them into database automatically.
Also some chore along the way
> [Chore] Support load oauth config from env

- frontend/src/features/ai/page/AIPage.tsx
- frontend/src/features/auth/components/AddOAuthDialog.tsx
- frontend/src/features/auth/components/OAuthConfigDialog.tsx
- frontend/src/features/dashboard/page/DashboardPage.tsx
- frontend/src/features/functions/components/SecretsContent.tsx
https://github.com/user-attachments/assets/3de87f5b-8be1-4477-a12d-3ba417704569
> [UI] Changed oauth config UI

- backend/src/api/routes/storage.ts
- backend/src/core/storage/storage.ts
- frontend/src/features/database/page/DatabasePage.tsx
- frontend/src/features/storage/page/StoragePage.tsx
Also remove the refresh button for cloud project according to [https://github.com/InsForge/insforge-cloud/issues/67](https://github.com/InsForge/insforge-cloud/issues/67)
> [Chore] Change delete object permission to check role

- docker-compose.prod.yml
- docker-compose.yml
i should've chekced more carefully. i just did a docker restart without env and everything still works,...
maybe there are unintended consequence.. so i changed to more than 32 char
> update docker compose
